/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.miapp.triage.gui;

import com.miapp.triage.metodoscsv.ltriage;
import com.miapp.triage.triage.Triage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 * Clase Moverpaciente
 * 
 * @author Fran
 */
public class Moverpaciente extends javax.swing.JFrame {

  /**
    * Ruta del archivo "triage.csv" utilizado en el programa.
    */
    String archivo = "src\\main\\java\\com\\miapp\\triage\\csv\\triage.csv";
    
    /**
     * instancia de clase ltriage
     */
    private ltriage gestorTriage;
    
    /**
     * Creates new form Moverpaciente
     */
    public Moverpaciente()  {
        initComponents();
        new ArrayList<Triage>();
        gestorTriage = new ltriage();
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        try {
            cargarPacientesDesdeArchivo(archivo);
            
            jComboBox1.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                cargarInformacionPaciente();
            }
        });
            
           jTextField2.getDocument().addDocumentListener(new DocumentListener() {
            public void actionPerformed(ActionEvent e) {
                jTextField2ActionPerformed(e);
            }

                @Override
                public void insertUpdate(DocumentEvent e) {
                    actualizarComboBox();
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    actualizarComboBox();
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                  
                }
        });
           
        } catch (IOException ex) {
            Logger.getLogger(Moverpaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Paciente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 60, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setBorder(null);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 57, 140, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre paciente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Urgencia actual");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 140, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 97, 140, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cambiar a");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 183, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setBorder(null);
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 180, 140, -1));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 137, 140, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(60, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 340));

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Mover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 10, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuDos men = new MenuDos();
        men.setVisible(true);
        men.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:

    String pacienteSeleccionado = jComboBox1.getSelectedItem().toString();
    
    long dniPacienteSeleccionado = Long.parseLong(pacienteSeleccionado);

    String nuevoTipoUrgencia = jComboBox2.getSelectedItem().toString();

    List<String> lineasActualizadas = new ArrayList<>();


    try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
        String linea;
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(";");
            if (datos.length >= 7) { 
                long dni = Long.parseLong(datos[6]);
                if (dni == dniPacienteSeleccionado) {

                    datos[1] = nuevoTipoUrgencia;
                }
                
                lineasActualizadas.add(String.join(";", datos));
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    }


    try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivo))) {
        for (String linea : lineasActualizadas) {
            writer.write(linea);
            writer.newLine();
        }
    } catch (IOException e) {
        e.printStackTrace();
    }

    JOptionPane.showMessageDialog(this, "Paciente movido con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed
   
    /**
    * encuentra id segun dni del paciente
    * @param dniSeleccionado dni seleccionado
    * @return id
    */
    private int encontrarIdPorDni(String dniSeleccionado) {

        int idEncontrado = -1;
   
    try (BufferedReader brPacientes = new BufferedReader(new FileReader(archivo))) {
        String lineaPacientes;
        while ((lineaPacientes = brPacientes.readLine()) != null) {
            System.out.println("Línea leída del archivo: " + lineaPacientes);
            String[] datosPacientes = lineaPacientes.split(";");
            if (datosPacientes.length >= 7) {
                String dni = datosPacientes[6];
                int id = Integer.parseInt(datosPacientes[0]);
                if (dniSeleccionado.equalsIgnoreCase(dni)) { // Comparación sin distinguir mayúsculas/minúsculas
                    idEncontrado = id;
                    System.out.println("ID buscado: " + id);
                    break;
                }
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    }

    return idEncontrado;
} 
    
    /**
    * actualiza color segun opcion combobox
    *
    * @return color
    */
    private void actualizarComboBox() {
        jComboBox2.removeAllItems();
        
        String urgenciaActual = jTextField2.getText();
                
        if ("Riesgo vital inmediato".equals(urgenciaActual)) {
            jComboBox2.addItem("Muy urgente");
            jComboBox2.addItem("Urgente");

        } else if ("Muy urgente".equals(urgenciaActual)) {
            jComboBox2.addItem("Riesgo vital inmediato");
            jComboBox2.addItem("Muy urgente");
            jComboBox2.addItem("Normal");

        } else if ("Urgente".equals(urgenciaActual)) {
            jComboBox2.addItem("Riesgo vital inmediato");
            jComboBox2.addItem("Muy urgente");
            jComboBox2.addItem("Normal");
            jComboBox2.addItem("No urgente");
        } else if ("Normal".equals(urgenciaActual)) {
            jComboBox2.addItem("Muy urgente");;
            jComboBox2.addItem("Urgente");;
            jComboBox2.addItem("No urgente");
        } else if ("No urgente".equals(urgenciaActual)) {
            jComboBox2.addItem("Urgente");
            jComboBox2.addItem("Normal");
        }
    }
        
    
    
    
    /**
    * carga pacientes desde un archivo
    * @param archivo archivo donde esta la informacion
    * @return pacientes
    */
    private void cargarPacientesDesdeArchivo(String archivo) throws IOException {
    BufferedReader br = null;
    try {
        br = new BufferedReader(new FileReader(archivo));
        String linea;
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(";");
            
            if (datos.length >= 6) {
                String Dni = datos[6];
                
             
                jComboBox1.addItem(Dni);
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    } finally {
        if (br != null) {
            br.close();
        }
    }
}                           
    /**
    * carga datos pacientes desde un archivo
    *
    * @return datos de pacientes
    */
    private void cargarInformacionPaciente(){
        
        String paciente = jComboBox1.getSelectedItem().toString();
        
        String infoColor = cargarColor(paciente);
        String nombrePaciente = cargarNombrePaciente(paciente);
        
        jTextField2.setText(infoColor);
        jTextField1.setText(nombrePaciente);
    }
    
    /**
    * carga color del paciente
    * @param paciente paciente
    * @return dato paciente
    */
    private String cargarColor(String paciente){
        try (BufferedReader br = new BufferedReader(new FileReader("src\\main\\java\\com\\miapp\\triage\\csv\\triage.csv"))) {
        String linea;
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(";");
            Long dni = Long.parseLong(datos[6]);
            if (dni.toString().equals(paciente)) {

                return datos[1]; 
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    

    return "Información no encontrada";
    }
    
    /**
    * carga nomrbe paciente desde un archivo
    * @param paciente paciente
    * @return nomrbe paciente
    */
    private String cargarNombrePaciente(String paciente){
        try (BufferedReader br = new BufferedReader(new FileReader("src\\main\\java\\com\\miapp\\triage\\csv\\triage.csv"))) {
        String linea;
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(";");
            String dni = datos[6];
            if (dni.equals(paciente)) {

                return datos[5]; 
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    

    return "Información no encontrada";
    }
    /**
     * metodo main
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Moverpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Moverpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Moverpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Moverpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Moverpaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
    * boton utilizado en la interfaz
    */
    private javax.swing.JButton jButton1;
    /**
    * boton utilizado en la interfaz
    */
    private javax.swing.JButton jButton2;
    /**
    * jcombobox utilizado en la interfaz
    */
    private javax.swing.JComboBox<String> jComboBox1;
    /**
    * jcombobox utilizado en la interfaz
    */
    private javax.swing.JComboBox<String> jComboBox2;
    /**
    * label utilizado en la interfaz
    */
    private javax.swing.JLabel jLabel1;
    /**
    * label utilizado en la interfaz
    */
    private javax.swing.JLabel jLabel2;
    /**
    * label utilizado en la interfaz
    */
    private javax.swing.JLabel jLabel4;
    /**
    * label utilizado en la interfaz
    */
    private javax.swing.JLabel jLabel5;
    /**
    * panel utilizado en la interfaz
    */
    private javax.swing.JPanel jPanel1;
    /**
    * panel utilizado en la interfaz
    */
    private javax.swing.JPanel jPanel2;
    /**
    * panel utilizado en la interfaz
    */
    private javax.swing.JPanel jPanel3;
    /**
    * jtextfield utilizado en la interfaz
    */
    private javax.swing.JTextField jTextField1;
    /**
    * jtextfield utilizado en la interfaz
    */
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
